---
- name: Grafana - Add repo file
  become: true
  ansible.builtin.template:
    src: grafana.repo.j2
    dest: "{{ repo_path }}/grafana.repo"
    mode: '644'
  tags:
    - monitoring
    - grafana

- name: Grafana - Install package
  become: true
  ansible.builtin.yum:
    name:
      - grafana
    state: present
  notify:
    - Start grafana
  tags:
    - monitoring
    - grafana

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Grafana - Add Prometheus datasource
  community.grafana.grafana_datasource:
    name: Prometheus
    grafana_url: http://localhost:3000
    grafana_user: "{{ grafuser }}"
    grafana_password: "{{ grafpassword }}"
    ds_type: prometheus
    ds_url: http://localhost:9090
    basic_auth_user: "{{ basic_user }}"
    basic_auth_password: "{{ basic_pass }}"
    state: present
  tags:
    - monitoring
    - grafana

- name: Grafana - Add MySQL datasource
  community.grafana.grafana_datasource:
    name: MySQL
    grafana_url: http://localhost:3000
    grafana_user: "{{ grafuser }}"
    grafana_password: "{{ grafpassword }}"
    ds_type: mysql
    ds_url: "{{ mysql_db_addr }}"
    database: "{{ mysql_database }}"
    user: "{{ mysql_user }}"
    additional_secure_json_data:
      password: "{{ mysql_pass }}"
    basic_auth_user: "{{ basic_user }}"
    basic_auth_password: "{{ basic_pass }}"
    state: present
  tags:
    - monitoring
    - grafana

- name: Grafana - Copy Node Exporter Dashboard
  ansible.builtin.copy:
    src: files/node-exporter-full.json
    dest: "{{ tmp_path }}/node-exporter-full.json"
    mode: '0644'
  tags:
    - monitoring
    - grafana

- name: Grafana - Import Node Exporter Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "{{ grafuser }}"
    grafana_password: "{{ grafpassword }}"
    state: present
    overwrite: false
    path: "{{ tmp_path }}/node-exporter-full.json"
  tags:
    - monitoring
    - grafana

- name: Grafana - Copy Mysqld Exporter Dashboard
  ansible.builtin.copy:
    src: files/mysql-overview.json
    dest: "{{ tmp_path }}/mysql-overview.json"
    mode: '0644'
  tags:
    - monitoring
    - grafana

- name: Grafana - Import Mysqld Exporter Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "{{ grafuser }}"
    grafana_password: "{{ grafpassword }}"
    state: present
    overwrite: false
    path: "{{ tmp_path }}/mysql-overview.json"
  tags:
    - monitoring
    - grafana

- name: Grafana - Copy Wordpress Stats Dashboard
  ansible.builtin.copy:
    src: files/wordpress-stats.json
    dest: "{{ tmp_path }}/wordpress-stats.json"
    mode: '0644'
  tags:
    - monitoring
    - grafana

- name: Grafana - Import Wordpress Stats Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "{{ grafuser }}"
    grafana_password: "{{ grafpassword }}"
    state: present
    overwrite: false
    path: "{{ tmp_path }}/wordpress-stats.json"
  tags:
    - monitoring
    - grafana
...
