---
- name: Check OS
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "7"
    fail_msg: Host {{ ansible_hostname }} does not meet minimal reqs

- name: Pretasks
  ansible.builtin.include_tasks: pretasks.yml
  tags: [always]

- name: Prometheus installation
  ansible.builtin.include_tasks: prometheus.yml
  tags: [always]

- name: Alertmanager installation
  ansible.builtin.include_tasks: alertmanager.yml
  tags: [always]

- name: Node Exporter
  ansible.builtin.include_tasks: exporter.yml
  tags: [always]

- name: Grafana Installation
  ansible.builtin.include_tasks: grafana.yml
  tags: [always]
...
