---
- name: Set timezone
  community.general.timezone:
    name: Europe/Moscow
  tags:
    - monitoring
    - pretasks

- name: Firewall - Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled
  tags:
    - monitoring
    - pretasks

- name: Firewall - Stop firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  tags:
    - monitoring
    - pretasks

- name: Hosts - Rename Hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - monitoring
    - pretasks

- name: Yum - Upgrade packages
  become: true
  ansible.builtin.yum:
    name: "*"
    enablerepo: base,updates,extras
    state: present
    update_cache: true
  tags:
    - monitoring
    - pretasks
...
