---
- name: Prometheus - Get release
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ arch }}.tar.gz"
    dest: "{{ prometheus_archive }}"
    mode: '0644'
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Add user
  become: true
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false
    create_home: false
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus
  with_items:
    - "{{ prometheus_path_conf }}"
    - "{{ prometheus_path_db }}"
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Extract archive
  ansible.builtin.unarchive:
    src: "{{ prometheus_archive }}"
    dest: "{{ tmp_path }}"
    remote_src: true
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Copy bianries to "{{ bin_path }}"
  become: true
  ansible.builtin.copy:
    src: "{{ prometheus_path_tmp }}/{{ item }}"
    dest: "{{ bin_path }}"
    remote_src: true
    mode: '0755'
    owner: prometheus
    group: prometheus
  with_items:
    - prometheus
    - promtool
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Copy directories to "{{ prometheus_path_conf }}"
  become: true
  ansible.builtin.copy:
    src: "{{ prometheus_path_tmp }}/{{ item }}"
    dest: "{{ prometheus_path_conf }}/"
    remote_src: true
    owner: prometheus
    group: prometheus
  with_items:
    - consoles
    - console_libraries
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Add config file
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_path_conf }}/prometheus.yml"
    mode: '644'
    owner: prometheus
    group: prometheus
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Add rules
  become: true
  ansible.builtin.copy:
    src: templates/rules.yml
    dest: "{{ prometheus_path_conf }}/rules.yml"
    mode: '644'
    owner: prometheus
    group: prometheus
  tags:
    - monitoring
    - prometheus

- name: Prometheus - Add Unit file
  become: true
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
    mode: '644'
  notify:
    - Reload daemon
    - Start prometheus
  tags:
    - monitoring
    - prometheus

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Remove Artifacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ prometheus_archive }}"
    - "{{ prometheus_path_tmp }}"
  tags:
    - monitoring
    - prometheus
...
